Repository Direwolf20-MC/BuildingGadgets, pull requests merged in 2019-02, with the labels that each got.

#218 Fix too large Templates being copied to Clipboard
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/templatemanager/TemplateManagerCommands.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/templatemanager/TemplateManagerGUI.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/GadgetUtils.java
Labels: oversight

#219 Fix potential, though unlikely, crash when changing the poweredByFE setting at runtime
  src/main/java/com/direwolf20/buildinggadgets/common/BuildingGadgets.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/templatemanager/TemplateManagerCommands.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/templatemanager/TemplateManagerGUI.java
  src/main/java/com/direwolf20/buildinggadgets/common/config/Config.java
  src/main/java/com/direwolf20/buildinggadgets/common/events/AnvilRepairHandler.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/capability/CapabilityProviderEnergy.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/capability/ItemEnergyForge.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetBuilding.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetCopyPaste.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetDestruction.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetExchanger.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetGeneric.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/ToolRenders.java
Labels: bug

#221 Add ability to bind a Refined Storage network to a gadget as a remote inventory.
  build.gradle
  gradle.properties
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetCopyPaste.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/GadgetUtils.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/NetworkExtractor.java
Labels: enhancement

#226 Make FieldWrappers internally type-safe to allow for proper checks
  src/main/java/com/direwolf20/buildinggadgets/common/config/fieldmap/FieldMapper.java
  src/main/java/com/direwolf20/buildinggadgets/common/config/fieldmap/FieldSerializer.java
  src/main/java/com/direwolf20/buildinggadgets/common/config/fieldmap/FieldWrapper.java
Labels: oversight

#224 Paste container enhancement - #211
  src/main/java/com/direwolf20/buildinggadgets/client/proxy/ClientProxy.java
  src/main/java/com/direwolf20/buildinggadgets/common/config/Config.java
  src/main/java/com/direwolf20/buildinggadgets/common/config/SyncedConfig.java
  src/main/java/com/direwolf20/buildinggadgets/common/events/ItemPickupHandler.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/ConstructionPasteContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/ConstructionPasteContainerT2.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/ConstructionPasteContainerT3.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/GenericPasteContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/ModItems.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/pastes/ConstructionPaste.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/pastes/ConstructionPasteContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/pastes/ConstructionPasteContainerCreative.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/pastes/GenericPasteContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/pastes/RegularPasteContainerTypes.java
  src/main/java/com/direwolf20/buildinggadgets/common/proxy/CommonProxy.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/ConstructionPasteRecipeHandler.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/InventoryManipulation.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/NBTTool.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/PasteContainerMeshDefinition.java
  src/main/resources/assets/buildinggadgets/lang/en_us.lang
  src/main/resources/assets/buildinggadgets/models/item/constructionpastecontainercreative.json
  src/main/resources/assets/buildinggadgets/textures/items/constructionpastecontainercreative.png
Labels: enhancement

#229 Add connected/unconnected surface/area mode to the building/exchanging/destruction gadgets.
  src/main/java/com/direwolf20/buildinggadgets/client/KeyBindings.java
  src/main/java/com/direwolf20/buildinggadgets/client/events/EventKeyInput.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/GuiButtonAction.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/GuiButtonColor.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/GuiButtonHelp.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/GuiButtonSelect.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/GuiButtonSound.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/ModeRadialMenu.java
  src/main/java/com/direwolf20/buildinggadgets/common/ModSounds.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/templatemanager/TemplateManagerGUI.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetBuilding.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetCopyPaste.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetDestruction.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetExchanger.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetGeneric.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/PacketAnchorKey.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/PacketChangeRange.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/PacketEmpty.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/PacketHandler.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/PacketRequestConfigSync.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/PacketToggleConnectedArea.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/PacketToggleFuzzy.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/PacketUndoKey.java
  src/main/java/com/direwolf20/buildinggadgets/common/proxy/CommonProxy.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/BuildingModes.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/ExchangingModes.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/GadgetUtils.java
  src/main/resources/assets/buildinggadgets/lang/en_us.lang
  src/main/resources/assets/buildinggadgets/sounds.json
  src/main/resources/assets/buildinggadgets/sounds/beep.ogg
  src/main/resources/assets/buildinggadgets/textures/ui/surface.png
Labels: enhancement

#230 Add Contribution.md (Closes #227)
  .gitignore
  CONTRIBUTION.md
Labels: enhancement

#241 Initial port of GUI and keybinding functionality.
  src/main/java/com/direwolf20/buildinggadgets/client/events/EventKeyInput.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/GuiMod.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/GuiProxy.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/ModeRadialMenu.java
  src/main/java/com/direwolf20/buildinggadgets/common/BuildingGadgets.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/templatemanager/TemplateManager.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/templatemanager/TemplateManagerContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/templatemanager/TemplateManagerGUI.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetCopyPaste.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetDestruction.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/packets/PacketAnchorKey.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/packets/PacketChangeRange.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/packets/PacketToggleConnectedArea.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/packets/PacketToggleFuzzy.java
Labels: 1.13, port

#251 First draft of package guidelines.
  CONTRIBUTION.md
Labels: enhancement

#252 Added mode for raytracing fluids for all gadgets, and mode for placing in or on blocks for the building gadget.
  src/main/java/com/direwolf20/buildinggadgets/client/gui/ModeRadialMenu.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetBuilding.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetCopyPaste.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetDestruction.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetExchanger.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetGeneric.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/PacketHandler.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/packets/PacketToggleBlockPlacement.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/packets/PacketToggleRayTraceFluid.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/ToolRenders.java
  src/main/java/com/direwolf20/buildinggadgets/common/tools/modes/BuildingModes.java
  src/main/java/com/direwolf20/buildinggadgets/common/utils/GadgetUtils.java
  src/main/java/com/direwolf20/buildinggadgets/common/utils/helpers/VectorHelper.java
  src/main/resources/assets/buildinggadgets/lang/en_us.json
Labels: 1.13, enhancement

#254 api - Merge build structure in
  build.gradle
  gradle.properties
  src/api/java/com/direwolf20/buildinggadgets/api/APITest.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/ConstructionBlock.java
  src/main/java/com/direwolf20/buildinggadgets/common/utils/helpers/InventoryHelper.java
  src/main/resources/META-INF/mods.toml
  src/main/resources/buildinggadgets_logo.png
  src/main/resources/mcmod.info
Labels: 1.13, cleanup, enhancement
