Repository Direwolf20-MC/BuildingGadgets, pull requests merged in 2019-09, with the labels that each got.

#362 Update README.md
  README.md
Labels: enhancement

#378 Updated contributing Guidelines
  CONTRIBUTION.md
Labels: cleanup, enhancement

#377 Registry rewrite
  build.gradle
  src/main/java/com/direwolf20/buildinggadgets/client/ClientProxy.java
  src/main/java/com/direwolf20/buildinggadgets/client/events/EventTooltip.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/CopyGUI.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/ModeRadialMenu.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/blocks/TemplateManagerGUI.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/components/GuiIconActionable.java
  src/main/java/com/direwolf20/buildinggadgets/client/models/ConstructionBakedModel.java
  src/main/java/com/direwolf20/buildinggadgets/client/renderer/EffectBlockTER.java
  src/main/java/com/direwolf20/buildinggadgets/common/BuildingGadgets.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/ChargingStation.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/ConstructionBlock.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/EffectBlock.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/TemplateManager.java
  src/main/java/com/direwolf20/buildinggadgets/common/blocks/TemplateManagerCommands.java
  src/main/java/com/direwolf20/buildinggadgets/common/containers/ChargingStationContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/containers/TemplateManagerContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/entities/ConstructionBlockEntity.java
  src/main/java/com/direwolf20/buildinggadgets/common/entities/ConstructionBlockEntityRender.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetBuilding.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetCopyPaste.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetDestruction.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/GadgetExchanger.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/renderers/BuildingRender.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/renderers/CopyPasteRender.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/renderers/DestructionRender.java
  src/main/java/com/direwolf20/buildinggadgets/common/items/gadgets/renderers/ExchangerRender.java
  src/main/java/com/direwolf20/buildinggadgets/common/network/packets/PacketCopyCoords.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/ClientConstructContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/OurBlocks.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/OurContainers.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/OurEntities.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/OurItems.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/OurSounds.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/RegistryContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/RegistryHandler.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/RegistryObjectBuilder.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/SimpleRegistryObjectBuilder.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/block/BlockBuilder.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/block/BlockRegistryContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/block/tile/TileEntityBuilder.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/block/tile/TileEntityRegistryContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/block/tile/TileEntityTypeBuilder.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/container/ScreenContainerBuilder.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/container/ScreenContainerObjectBuilder.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/container/ScreenContainerRegistryContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/entity/EntityBuilder.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/entity/EntityRegistryContainer.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/objects/BGBlocks.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/objects/BGContainers.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/objects/BGEntities.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/objects/BGItems.java
  src/main/java/com/direwolf20/buildinggadgets/common/registry/objects/BuildingObjects.java
  src/main/java/com/direwolf20/buildinggadgets/common/tiles/ChargingStationTileEntity.java
  src/main/java/com/direwolf20/buildinggadgets/common/tiles/ConstructionBlockTileEntity.java
  src/main/java/com/direwolf20/buildinggadgets/common/tiles/EffectBlockTileEntity.java
  src/main/java/com/direwolf20/buildinggadgets/common/tiles/TemplateManagerTileEntity.java
  src/main/java/com/direwolf20/buildinggadgets/common/util/buffers/PasteToolBufferBuilder.java
  src/main/java/com/direwolf20/buildinggadgets/common/util/helpers/InventoryHelper.java
  src/main/java/com/direwolf20/buildinggadgets/common/util/tools/modes/ExchangingMode.java
Labels: 1.14, cleanup

#361 Port 1.13 material list
  src/api/java/com/direwolf20/buildinggadgets/api/materials/MaterialList.java
  src/api/java/com/direwolf20/buildinggadgets/api/materials/UniqueItem.java
  src/main/java/com/direwolf20/buildinggadgets/client/events/EventKeyInput.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/GuiMod.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/base/EntryList.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/base/GuiEntryList.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/materiallist/MaterialListGUI.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/materiallist/ScrollingMaterialList.java
  src/main/java/com/direwolf20/buildinggadgets/client/gui/materiallist/SortingModes.java
  src/main/java/com/direwolf20/buildinggadgets/common/util/lang/MaterialListTranslation.java
  src/main/resources/assets/buildinggadgets/lang/en_us.json
  src/main/resources/assets/buildinggadgets/textures/gui/material_list.png
Labels: 1.14, enhancement
